CREATE TABLE IF NOT EXISTS master_records (
    id SERIAL PRIMARY KEY,
    sn TEXT,
    pn TEXT,
    model TEXT,
    work_station_process TEXT,
    baseboard_sn TEXT,
    baseboard_pn TEXT,
    number_of_times_baseboard_is_used INTEGER,
    workstation_name TEXT,
    history_station_start_time TIMESTAMP,
    history_station_end_time TIMESTAMP,
    history_station_passing_status TEXT,
    operator TEXT,
    failure_reasons TEXT,
    failure_note TEXT,
    failure_code TEXT,
    diag_version TEXT,
    fixture_no TEXT,
    customer_pn TEXT,
    outbound_version TEXT,
    hours TEXT,
    service_flow TEXT,
    passing_station_method TEXT,
    first_station_start_time TIMESTAMP,
    day INTEGER,
    data_source TEXT NOT NULL
); 